# Generated by Django 4.2.4 on 2023-10-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Koder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_created=True)),
                ('created_at', models.DateField(auto_created=True, auto_now=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=350)),
                ('generation', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], default='m', max_length=8)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
