# Generated by Django 4.2.4 on 2023-10-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now=True)),
                ('number', models.IntegerField()),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='bootcamp.bootcamp')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=350)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('generations', models.ManyToManyField(related_name='mentors', to='bootcamp.generation')),
            ],
        ),
        migrations.CreateModel(
            name='Koder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=350)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'In-active'), ('finished', 'Finished')], default='active', max_length=8)),
                ('size', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], default='m', max_length=8)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='koders', to='bootcamp.generation')),
            ],
        ),
    ]
