# Generated by Django 4.2.4 on 2023-10-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
