# Generated by Django 4.2.6 on 2023-10-28 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_created=True, auto_now=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=27)),
                ('biography', models.TextField(max_length=255)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_created=True, auto_now=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=27)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_created=True, auto_now=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='app.patient')),
                ('psychologist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='app.psychologist')),
            ],
        ),
    ]
